- README.md
- docs/_config.yml
- docs/_sass/minima/_base.scss
- docs/index.md
* Jekyll config
* Page title
* Tab title
* README contents
> Update project page settings

- src/main/java/seedu/address/logic/commands/RemarkCommand.java
Remove the empty RemarkCommand class added.
> Remove RemarkCommand class

- src/main/java/seedu/address/logic/commands/transaction/ClearTransactionsCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/transaction/DeleteTransactionCommandParser.java
- src/main/java/seedu/address/model/Model.java
- src/test/java/seedu/address/logic/commands/transaction/ClearTransactionsCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
> Add clear transactions command functionality

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/UniCashMessages.java
- src/main/java/seedu/address/logic/commands/transaction/GetTotalExpenditureCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/transaction/GetTotalExpenditureCommandParser.java
- src/test/java/seedu/address/logic/commands/transaction/GetTotalExpenditureCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
> Add "Get total expenditure" command

- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/transaction/ListCommandParser.java
- src/test/java/seedu/address/logic/commands/ListCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
> Add List Command for Transactions

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
> Add Find Command for Transactions

- src/main/java/seedu/address/logic/commands/transaction/GetTotalExpenditureCommand.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/transaction/DateTime.java
- src/test/java/seedu/address/logic/commands/transaction/GetTotalExpenditureCommandTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/transaction/CategoryTest.java
- src/test/java/seedu/address/model/transaction/DateTimeTest.java
- src/test/java/seedu/address/model/transaction/LocationTest.java
1. Fix hidden exception throwing for invalid dateTime 
2. Change the handling of invalid values in by Parser
> Update handling of invalid values for non-compulsary fields

- docs/DeveloperGuide.md
Change all references of Expense and Income to Transactions, and merge some Use Cases while adding some additional Use Cases for the new UniCa$h Commands.
> Update Developer guide to Transactions instead of Expense or Income

- src/main/java/unicash/MainApp.java
- src/main/java/unicash/ui/MainWindow.java
- src/main/java/unicash/ui/StyleSheet.java
- src/main/java/unicash/ui/TransactionCard.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
- src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
- src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
- src/test/java/unicash/storage/StorageManagerTest.java
Minor UI details to TransactionCard and some internal changes to the code base to make styling of individual elements of the TransactionCard more flexible.
As before, given the unfortunate state of UI and Unit Testing, I'm proposing to merge regardless of codecov status.
> Updates to TransactionCard GUI and code

- src/main/java/unicash/commons/enums/BudgetInterval.java
- src/main/java/unicash/commons/enums/TransactionType.java
- src/main/java/unicash/logic/commands/EditTransactionCommand.java
- src/main/java/unicash/logic/parser/AddTransactionCommandParser.java
- src/main/java/unicash/logic/parser/ParserUtil.java
- src/main/java/unicash/model/budget/Budget.java
- src/main/java/unicash/model/budget/Interval.java
- src/main/java/unicash/model/commons/Amount.java
- src/main/java/unicash/model/transaction/Transaction.java
- src/main/java/unicash/model/util/SampleDataUtil.java
- src/main/java/unicash/storage/JsonAdaptedTransaction.java
- src/main/java/unicash/ui/TransactionCard.java
- src/test/java/unicash/logic/parser/AddTransactionCommandParserTest.java
- src/test/java/unicash/logic/parser/EditTransactionCommandParserTest.java
- src/test/java/unicash/logic/parser/ParserUtilTest.java
- src/test/java/unicash/model/budget/BudgetTest.java
- src/test/java/unicash/model/budget/IntervalTest.java
- src/test/java/unicash/model/commons/AmountTest.java
- src/test/java/unicash/storage/JsonAdaptedTransactionTest.java
- src/test/java/unicash/testutil/BudgetBuilder.java
- src/test/java/unicash/testutil/EditTransactionDescriptorBuilder.java
- src/test/java/unicash/testutil/TransactionBuilder.java
- src/test/java/unicash/testutil/TypicalBudgets.java
Creates Budget Model
- Budget class
- Interval class
- BudgetInterval enum (day, week, month)
Refactored Amount class to unicash.model.commons
> Budget Model

- docs/DeveloperGuide.md
- Developer Guide skeleton has been added
- NFRs have been transferred over
> [Documentation PR] Add Developer Guide Skeleton

- src/main/java/unicash/ui/CommandBox.java
- src/test/java/unicash/ui/CommandBoxUiTest.java
- CommandBox can now restore the input in the command text field as opposed to replacing it with a blank input
- UI Unit Tests added
> [Patch] Update CommandBox History

- src/main/java/unicash/logic/commands/TestCommand.java
- src/main/java/unicash/logic/parser/UniCashParser.java
- src/main/java/unicash/model/util/SampleDataUtil.java
- TestCommand added, activate with `test`
- Test transactions added to SampleDataUtil, feel free to add more with subsequent PRs
- TestCommand will be removed before final release.
- TestTransactions can also be used for unit testing purposed.
> [For Test-branch] Add Test Command

- src/main/java/unicash/model/util/SampleDataUtil.java
- Add TestTransactions for more extensive unit testing
> Add TestTransactions

- src/main/java/unicash/logic/UniCashMessages.java
- src/main/java/unicash/logic/commands/ClearTransactionsCommand.java
- src/main/java/unicash/logic/commands/ExitCommand.java
- src/main/java/unicash/logic/commands/HelpCommand.java
- src/main/java/unicash/logic/commands/ResetCommand.java
- src/main/java/unicash/logic/parser/HelpCommandParser.java
- src/main/java/unicash/logic/parser/UniCashParser.java
- src/test/java/unicash/logic/commands/HelpCommandTest.java
- src/test/java/unicash/logic/parser/HelpCommandParserTest.java
Allow for getting help for specific command
> Help Command for specified commands

- src/main/java/unicash/logic/commands/GetBudgetCommand.java
- src/test/java/unicash/logic/commands/GetBudgetCommandTest.java
Fixed so it's not `$-5.00` anymore
> Support negative budget amount

- docs/DeveloperGuide.md
- docs/UserGuide.md
- User Guide: https://woojiahao.com/tp/UserGuide.html
- Developer Guide: https://woojiahao.com/tp/DeveloperGuide.html
> Migrate to new layout

- docs/UserGuide.md
1. Remove screenshots for `add` and `help`
2. Update documentation for `edit` for `Category`
3. Fix `help` command example output
> Fix user reported bugs

- src/test/java/unicash/logic/parser/SetBudgetCommandParserTest.java
- src/test/java/unicash/model/budget/BudgetTest.java
- src/test/java/unicash/model/transaction/TransactionTest.java
Covered `SetBudgetParserTest`, `BudgetTest`, `TransactionTest`.
> Add and Enhance Unit Tests

- src/main/java/unicash/commons/enums/CommandType.java
As approved by prof, see: https://github.com/nus-cs2103-AY2324S1/forum/issues/421
> Add $ back for GetTotalExpenditure
